[build]
  functions = "lambda"
  publish = "public/"

[functions]
  node_bundler = "esbuild"
  included_files = ["cache/**/*", "data/**/*"]

[build.processing.js]
  bundle = false
  minify = false  

